version: "3.9"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - back-tier

networks:
  back-tier:
    external: true
    name: back-tier