version: '3.9'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - /mnt/storage1/fabric-data:/data
    environment:
      VERSION: "1.18.2"
      FABRIC_LAUNCHER_VERSION: "0.10.2"
      FABRIC_LOADER_VERSION: "0.13.3"
      EULA: "TRUE"
      TYPE: FABRIC
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      VIEW_DISTANCE: "8"
      SEED: "981506332"
      MOTD: "Mojangの奇妙冒险"
      TZ: "Asia/Shanghai"
      ONLINE_MODE: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      MEMORY: "3G"
      JVM_OPTS: "--add-modules jdk.incubator.vector -javaagent:authlib-injector-1.1.43.jar=https://littleskin.cn/api/yggdrasil"
      JVM_XX_OPTS: ""
    restart: unless-stopped
    networks:
      - back-tier

networks:
  back-tier:
    external: true
    name: back-tier
